/** Premium Peptides Lab — email design tokens (aligned with lib/design-system.ts) */
export const emailTheme = {
  primary: '#4A9FE8',
  primaryDark: '#2D7AB8',
  deep: '#2D3A52',
  mint: '#34D399',
  violet: '#A78BFA',
  energy: '#D4A012',
  canvas: '#E8EEF4',
  card: '#FFFFFF',
  surface: '#F4F7FB',
  border: '#E2E8F0',
  text: '#0F172A',
  textSecondary: '#475569',
  muted: '#64748B',
  successBg: '#ECFDF5',
  successBorder: '#A7F3D0',
  successText: '#047857',
  warnBg: '#FFFBEB',
  warnBorder: '#FDE68A',
  warnText: '#92400E',
  fontSans: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  fontMono: "ui-monospace, 'SF Mono', Menlo, Consolas, monospace",
  radius: '12px',
  radiusLg: '16px',
} as const;
